name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '10 * * * *'


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1

    - name: 'Get weather report'
      run:  curl "https://wttr.in/Guicheng?format=4&m" -o guicheng.html

    - name: 'push html'
      run:  git config --global user.email "ye.123789456@gmail.com"
      run:  git config --global user.name "yexiang"
      run:  git add . && git commit -m 'init' && git push

