name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '20 * * * *'


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1


    - name: 'rm ...'
      run:  rm -rf /tmp/yy   

    - name: 'clone'
      run:  git config --global user.email "ye.123789456@gmail.com" && git config --global user.name "yexiang" && git clone https://github.com/yexiang/yexiang.github.io /tmp/yy

    - name: 'Get weather report'
      run:  curl "https://wttr.in/Guicheng?format=4&m" -o /tmp/yy/guicheng.html

    - name: 'push html'
      run:  cd /tmp/yy && git add . && git commit -m "initial commit" && git push   


