name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '20 * * * *'


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1

    - name: 'Get weather report'
      run:  curl "https://wttr.in/Guicheng?format=4&m" -o guicheng.html

    - name: 'push html'
      run:  curl -T guicheng.html ftp://unaux_23374971:znkvzshg6@ftp.unaux.com/htdocs/public/guicheng.txt
 
